/*
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.inf.kortargyalo.drones.behavior.xtext.ui;

import com.google.inject.Injector;
import hu.bme.mit.inf.kortargyalo.drones.behavior.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DroneScriptExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return XtextActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return XtextActivator.getInstance().getInjector(XtextActivator.HU_BME_MIT_INF_KORTARGYALO_DRONES_BEHAVIOR_XTEXT_DRONESCRIPT);
	}
	
}
