<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="droneModel" nsURI="http://hu.bme.mit.inf.kortargyalo.drones.model"
    nsPrefix="droneModel">
  <eClassifiers xsi:type="ecore:EClass" name="DroneModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenarios" upperBound="-1"
        eType="#//Scenario" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dronetypes" upperBound="-1"
        eType="#//DroneType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scripts" upperBound="-1"
        eType="#//Script" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="capabilityTypes" upperBound="-1"
        eType="#//CapabilityType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DroneType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="capabilities" upperBound="-1"
        eType="#//Capability" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimension" lowerBound="1"
        eType="#//AABB" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scenario">
    <eStructuralFeatures xsi:type="ecore:EReference" name="goals" upperBound="-1"
        eType="#//Goal" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environment" lowerBound="1"
        eType="#//Environment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scripts" upperBound="-1"
        eType="#//Script" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Goal"/>
  <eClassifiers xsi:type="ecore:EClass" name="Environment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="obstacles" upperBound="-1"
        eType="#//PhysicalObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" lowerBound="1"
        eType="#//Point" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dimension" lowerBound="1"
        eType="#//AABB" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Script">
    <eStructuralFeatures xsi:type="ecore:EReference" name="drone" lowerBound="1" eType="#//Drone"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AABB">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="depth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Point">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="z" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Capability">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//CapabilityType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxmimalValue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="energyConsumptionPerValue"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CapabilityType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Drone">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//DroneType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" upperBound="-1"
        eType="#//Point" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeStatement" eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="StatementSequence" eSuperTypes="#//CompositeStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalStatement" eSuperTypes="#//CompositeStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Loop" eSuperTypes="#//CompositeStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="AtomicStatement" eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CooperativeActionStatement" eSuperTypes="#//AtomicStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//CooperativeActionType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roleByStatement" lowerBound="1"
        eType="#//Role"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SoloActionStatement" eSuperTypes="#//AtomicStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Move" eSuperTypes="#//SoloActionStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Charge" eSuperTypes="#//SoloActionStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Role">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirements" eType="#//Requirement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CooperativeActionType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//Role" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Requirement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimalValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//CapabilityType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Signal" eSuperTypes="#//SoloActionStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signaltype" eType="#//SignalType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WaitForSignal" eSuperTypes="#//SoloActionStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reactionstatement" upperBound="-1"
        eType="#//ReactionStatement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SignalType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReactionStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reactoTo" eType="#//SignalType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reaction" lowerBound="1"
        eType="#//Statement"/>
  </eClassifiers>
</ecore:EPackage>
