/*
 * generated by Xtext 2.9.1
 */
package hu.bme.mit.inf.kortargyalo.drones.behavior.xtext.validation

import org.eclipse.xtext.validation.Check
import hu.bme.mit.inf.kortargyalo.drones.behavior.dronesBehavior.SendSignal
import hu.bme.mit.inf.kortargyalo.drones.behavior.dronesBehavior.DronesBehaviorPackage
import org.eclipse.xtext.EcoreUtil2
import hu.bme.mit.inf.kortargyalo.drones.behavior.dronesBehavior.Script

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class DroneScriptValidator extends AbstractDroneScriptValidator {
	
	@Check
	def checkGreetingStartsWithCapital(SendSignal signalCommand) {
		if (signalCommand.recipent == EcoreUtil2.getContainerOfType(signalCommand, Script)?.drone) {
			warning('Signals sent to from a drone to itself will be dropped', 
					signalCommand,
					DronesBehaviorPackage.eINSTANCE.sendSignal_Recipent)
		}
	}
	
}
