/*
 * generated by Xtext 2.9.1
 */
package hu.bme.mit.inf.kortargyalo.drones.behavior.xtext.parser.antlr;

import com.google.inject.Inject;
import hu.bme.mit.inf.kortargyalo.drones.behavior.xtext.parser.antlr.internal.InternalDroneScriptParser;
import hu.bme.mit.inf.kortargyalo.drones.behavior.xtext.services.DroneScriptGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class DroneScriptParser extends AbstractAntlrParser {

	@Inject
	private DroneScriptGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDroneScriptParser createParser(XtextTokenStream stream) {
		return new InternalDroneScriptParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "DronesBehavior";
	}

	public DroneScriptGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DroneScriptGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
